services:
  schnappster:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schnappster
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true