"""add seller and location fields to ads

Revision ID: 089655cf8d2c
Revises: 79894aa35617
Create Date: 2026-03-03 13:08:20.699324

"""
from typing import Sequence, Union

# pyright: reportMissingImports=false
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '089655cf8d2c'
down_revision: Union[str, Sequence[str], None] = '79894aa35617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ads', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ads', sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ads', sa.Column('shipping_cost', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ads', sa.Column('seller_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ads', sa.Column('seller_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ads', sa.Column('seller_rating', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ads', sa.Column('seller_is_friendly', sa.Boolean(), nullable=False))
    op.add_column('ads', sa.Column('seller_is_reliable', sa.Boolean(), nullable=False))
    op.add_column('ads', sa.Column('seller_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ads', sa.Column('seller_active_since', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('ads', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('location', sa.VARCHAR(), nullable=True))
    op.drop_column('ads', 'seller_active_since')
    op.drop_column('ads', 'seller_type')
    op.drop_column('ads', 'seller_is_reliable')
    op.drop_column('ads', 'seller_is_friendly')
    op.drop_column('ads', 'seller_rating')
    op.drop_column('ads', 'seller_url')
    op.drop_column('ads', 'seller_name')
    op.drop_column('ads', 'shipping_cost')
    op.drop_column('ads', 'condition')
    op.drop_column('ads', 'city')
    op.drop_column('ads', 'postal_code')
    # ### end Alembic commands ###
