"""add scrape_interval_minutes to adsearch

Revision ID: b101d1b0c493
Revises: 089655cf8d2c
Create Date: 2026-03-03 15:26:27.255682

"""
from typing import Sequence, Union

# pyright: reportMissingImports=false
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b101d1b0c493'
down_revision: Union[str, Sequence[str], None] = '089655cf8d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_searches', sa.Column('scrape_interval_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_searches', 'scrape_interval_minutes')
    # ### end Alembic commands ###
